### ISSUE TITLE
Fail to install IPinquiry4 package

### ISSUE THREAD

**Issue by Isabel-ql** [hzuber67/IPinquiry4#2]
Hi,

I'd like to analyse my mass spec data with IPinquiry4 package in R, however, I could't install the package. The error says that dependency 'edgeR' is not available for package 'IPinquiry4'. See the screenshot below. Could anybody help to solve this problem? Thanks very much!

Best,
Qun
<img width="609" alt="Screenshot 2023-12-11 at 18 37 07" src="https://github.com/hzuber67/IPinquiry4/assets/65905482/f5bc6e63-4924-4822-9c38-a110afa879c2">

**Comment by hzuber67** [comment]
Hi,

Install the package EdgeR first and then try again to install the IPinquiry package.

Best

Hélène

**Comment by Isabel-ql** [comment]
Hi!

Yes, I installed edgeR first and it works now! Thank you very much!

Best,
Qun

From: hzuber67 ***@***.***>
Reply to: hzuber67/IPinquiry4 ***@***.***>
Date: Monday, 11 December 2023 at 19:29
To: hzuber67/IPinquiry4 ***@***.***>
Cc: "Qun Liu (JIC)" ***@***.***>, Author ***@***.***>
Subject: Re: [hzuber67/IPinquiry4] Fail to install IPinquiry4 package (Issue #2)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi,

Install the package EdgeR first and then try again to install the IPinquiry package.

Best

Hélène
